/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Phone(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('Models/Phone/Phone.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]} scale={[0, 0, 0]}>
        <group position={[7.62, -21.09, 12.18]}>
          <mesh material={materials['Cisco_Phone_CP_6941_plastic_black.001']} geometry={nodes.Object_12001.geometry} />
        </group>
        <group position={[10.64, -21.09, 12.18]}>
          <mesh material={materials['Cisco_Phone_CP_6941_plastic_black.001']} geometry={nodes.Object_14001.geometry} />
        </group>
        <group position={[13.7, -21.09, 12.18]}>
          <mesh material={materials['Cisco_Phone_CP_6941_plastic_black.001']} geometry={nodes.Object_16001.geometry} />
        </group>
        <group position={[16.72, -21.09, 12.18]}>
          <mesh material={materials['Cisco_Phone_CP_6941_plastic_black.001']} geometry={nodes.Object_18001.geometry} />
        </group>
        <group position={[20.74, -25.19, 15.62]}>
          <mesh material={materials['Cisco_Phone_CP_6941_plastic_black.001']} geometry={nodes.Object_20001.geometry} />
          <mesh material={materials['Cisco_Phone_CP_6941_button_lamp.001']} geometry={nodes.Object_21001.geometry} />
        </group>
        <group position={[20.74, -23.51, 14.21]}>
          <mesh material={materials['Cisco_Phone_CP_6941_plastic_black.001']} geometry={nodes.Object_23001.geometry} />
          <mesh material={materials['Cisco_Phone_CP_6941_button_lamp.001']} geometry={nodes.Object_24001.geometry} />
        </group>
        <group position={[3.63, -25.19, 15.62]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
          <mesh material={materials['Cisco_Phone_CP_6941_plastic_black.001']} geometry={nodes.Object_26001.geometry} />
          <mesh material={materials['Cisco_Phone_CP_6941_button_lamp.001']} geometry={nodes.Object_27001.geometry} />
        </group>
        <group position={[3.63, -23.51, 14.21]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
          <mesh material={materials['Cisco_Phone_CP_6941_plastic_black.001']} geometry={nodes.Object_29001.geometry} />
          <mesh material={materials['Cisco_Phone_CP_6941_button_lamp.001']} geometry={nodes.Object_30001.geometry} />
        </group>
        <mesh material={materials['Cisco_Phone_CP_6941_red.001']} geometry={nodes.Object_10001.geometry} />
        <mesh material={materials['Cisco_Phone_CP_6941_plastic_black.001']} geometry={nodes.Object_5001.geometry} />
        <mesh material={materials['Cisco_Phone_CP_6941_labels.001']} geometry={nodes.Object_6001.geometry} />
        <mesh material={materials['Cisco_Phone_CP_6941_whire.001']} geometry={nodes.Object_7001.geometry} />
        <mesh material={materials['Cisco_Phone_CP_6941_glass.001']} geometry={nodes.Object_8001.geometry} />
        <mesh material={materials['Cisco_Phone_CP_6941_display.001']} geometry={nodes.Object_9001.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('Models/Phone/Phone.gltf')
